//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMT.API_DATA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        public int Id { get; set; }
        public string HOTEN { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public string SODIENTHOAI { get; set; }
        public string CHUNGMINHTHUNHANDAN { get; set; }
        public Nullable<int> LOAIPHONG { get; set; }
        public Nullable<int> SOKHACH { get; set; }
        public Nullable<System.DateTime> NGAYDEN { get; set; }
        public Nullable<System.DateTime> NGAYDI { get; set; }
        public string QUOCTICH { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<int> BOPHANGUIDEN { get; set; }
        public string NOIDUNG { get; set; }
    }
}
