//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMT.API_DATA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINDULICH
    {
        public int Id { get; set; }
        public string TIEUDE { get; set; }
        public string NOIDUNG { get; set; }
        public string MOTA { get; set; }
        public string HINHANH { get; set; }
        public string NGUOITAO { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string NGUOISUA { get; set; }
        public Nullable<System.DateTime> NGAYSUA { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
    }
}
